### ISSUE TITLE
self attention Pca map

### ISSUE THREAD

**Issue by leoShen917** [MichalGeyer/plug-and-play#21]
Hello,
Thanks for the wonderful work!! When I was visualizing the PCA of the self-attention map, I found that it could not achieve the same effect as in the PnP paper, that is, it could not share the spatial distribution with the input image.

![pca0](https://github.com/MichalGeyer/plug-and-play/assets/83259959/c4047d8d-63fa-4a34-97dc-50a910d8f987)

If I directly average the resulting self-attention map (8 attention heads) and visualise it, the result is shown below, with some highlighting at the diagonals.
![attention_map0](https://github.com/MichalGeyer/plug-and-play/assets/83259959/45cdd534-1de1-4920-ae4b-5bf6de1e4566)

As I understand it, each row of the self-attention map is a query of one feature of q for the entire k map. The diagonal of self attention map corresponds to the feature doing the query at the same position of q and k. Because the values are the same so the similarity is high, it's a white dot at the diagonal. I would like to ask how this kind of graph has the same spatial distribution as the input image?
Maybe I misunderstood, please give me some advice!

Looking forward to your apply.

**Comment by leoShen917** [comment]
Maybe I understand now.  PCA is not done on 8 attention heads, but on the feature dimension of q or k after averaging the 8 attention heads. I found that principal component analysis of the features of q or k, respectively, came out with a consistent spatial distribution with the input image.

**Comment by tnarek** [comment]
hi @leoShen917 , thanks for the question. The PCA is applied on the self-attention matrix itself. For example, if the self-attention matrix is of shape `(H*W) x (H*W)`, you can think of it as a set of `d=H*W`-dimensional vectors of size `n=H*W`. So we compute the 3  leading principal component vectors in the `d` dimension, and afterwards we project the `d`-dimensional vectors from the `n`-sized set to each of the leading components. This gives us a `n x 3`- dimensional matrix, which we reshape to `H x W x 3` and visualize as an RGB.

You can take a look at the visualization code [here](https://github.com/MichalGeyer/plug-and-play/blob/main/run_self_attn_pca.py). Let us know if you have more questions.

**Comment by leoShen917** [comment]
@tnarek Thanks for your reply. I will now close this issue.
