### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by Hickey8** [MichalGeyer/plug-and-play#24]
OSError: Can't load feature extractor for 'CompVis/stable-diffusion-safety-checker'. If you were trying to load it from 'https://huggingface.co/models', make sure you don't have a local directory with the same name. Otherwis
e, make sure 'CompVis/stable-diffusion-safety-checker' is the correct path to a directory containing a preprocessor_config.json file

**Comment by zjp-zjp-zjp** [comment]
Where are you from? If you are in China, try adding "HF_ENDPOINT=https://hf-mirror.com" before your python command, for example, HF_ENDPOINT=https://hf-mirror.com python run_features_extraction.py --config FEconfig.yaml

**Comment by Hickey8** [comment]
@zjp-zjp-zjp Thanks! it did work.
