### ISSUE TITLE
Parse block string

### ISSUE THREAD

**Issue by m-mandel** [MichalGeyer/plug-and-play#3]
https://github.com/MichalGeyer/plug-and-play/blob/2598b6536cd8bd338ee04b7b4ef5155bec628195/run_self_attn_pca.py#L19

Should be 
block_idx = int(block.split('_')[-1])

To allow for parsing of multiple digits (e.g. output_block_11)

**Comment by tnarek** [comment]
Fixed the block parsing, thanks!
