### ISSUE TITLE
RuntimeError: CUDA out of memory

### ISSUE THREAD

**Issue by kira3007** [MichalGeyer/plug-and-play#4]
Use A10，I got an error.   I don't know which GPU can run successfully

**Comment by apolinario** [comment]
I got this error too with multiple prompts. It tries to run all prompts in parallel, not in sequence. Try reducing the number of prompts and will probably work

**Comment by tnarek** [comment]
hi @kira3007, the default configurations of PnP include multiple translations in a single batch. As @apolinario mentioned, you can modify the config to have only one target prompt, which will reduce the GPU memory requirements.

We will soon release a Diffusers implementation of Plug-and-Play, which will be more efficient in terms of memory and runtime.

**Comment by kira3007** [comment]
> 

It works with single prompt, thank you very much

**Comment by sakshamjindal** [comment]
When will diffusers implementation of Plug-and-Play be available ?
