### ISSUE TITLE
A question about the model choice

### ISSUE THREAD

**Issue by MaayanBogin** [MichalGeyer/plug-and-play#8]
I'm currently writing a google colab demo for this code and I was wondering if the code will run as expected from custom trained models or third party models (stable diffusion models) because in this repo you are using an outdated version of SD

Thank you and have a nice day :)

**Comment by MaayanBogin** [comment]
Currently running on a T4 and running out of memory, Ill wait till Diffusers are implemented on this repo :)

**Comment by prometx11** [comment]
I tested this method on a custom trained (Dreambooth) 1.5 model, works well.

**Comment by tnarek** [comment]
Hi @MaayanBogin, for ocupying less memory, you can also set the `prompts` parameter in `pnp-real.yaml` and in `pnp-generated.yaml` to contain only one translation prompt.

Note that the current implementation works with any instance of StableDiffusion instance as long as it shares the same architecture and implementation as StableDiffusion v1-4.
